using hub_client.Stuff;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace hub_client.Helpers
{
    public static class BoosterManager
    {
        public static List<string> BoosterEditionList = new List<string>();
        public static List<string> BoosterPackList = new List<string>();
        public static List<string> ArsenalMysterieuxList = new List<string>();
        public static List<string> PackDuellisteList = new List<string>();
        public static List<string> DeckStructureList = new List<string>();
        public static List<string> DeckDeDemarrageList = new List<string>();
        public static List<string> GoldPremiumList = new List<string>();
        public static List<string> BattlePackList = new List<string>();
        public static List<string> BoosterSpecial = new List<string>();
        public static List<string> TournoiList = new List<string>();

        public static void LoadList()
        {
            BoosterEditionList.Clear();
            BoosterPackList.Clear();
            ArsenalMysterieuxList.Clear();
            PackDuellisteList.Clear();
            DeckStructureList.Clear();
            DeckDeDemarrageList.Clear();
            GoldPremiumList.Clear();
            BoosterSpecial.Clear();
            BattlePackList.Clear();
            TournoiList.Clear();

                BoosterEditionList.Add("La Légende du Dragon Bleu Aux Yeux Bleus (LOB)");
                BoosterEditionList.Add("Metal Raider (MRD)");
                BoosterEditionList.Add("Maître des Magies (MRL)");
                BoosterEditionList.Add("Serviteur du Pharaon (PSV)");
                BoosterEditionList.Add("Labyrinthe des Cauchemards (LON)");
                BoosterEditionList.Add("Héritage des Ténèbres (LOD)");
                BoosterEditionList.Add("Pharaonic Guardian (PGD)");
                BoosterEditionList.Add("Magician's Force (MFC)");
                BoosterEditionList.Add("La Crise des Ténèbres (DCR)");
                BoosterEditionList.Add("Invasion des Ténèbres (IOC)");
                BoosterEditionList.Add("L'Ame du Duelliste (SOD)");
                BoosterEditionList.Add("Sanctuaire Ancestral (AST)");
                BoosterEditionList.Add("Génèse Ténébreuse 1 (DB1)");
                BoosterEditionList.Add("Avénement du Destin (RDS)");
                BoosterEditionList.Add("Eternité Brûlante (FET)");
                BoosterEditionList.Add("Sombre Révélation 1 (DR1)");
                BoosterEditionList.Add("Le Millénaire Perdu (TLM)");
                BoosterEditionList.Add("Génèse Ténébreuse 2 (DB2)");
                BoosterEditionList.Add("Révolution Cybernétique (CRV)");
                BoosterEditionList.Add("Sombre Révélation 2 (DR2)");
                BoosterEditionList.Add("Energie Elémentaire (EEN)");
                BoosterEditionList.Add("L'ombre de l'Infini (SOI)");
                BoosterEditionList.Add("Puissance du Duelliiste (POTD)");
                BoosterEditionList.Add("Impact des Cyberténèbres (CDIP)");
                BoosterEditionList.Add("Sombre Révélation 3 (DR3)");
                BoosterEditionList.Add("Ennemi du bien (EOJ)");
                BoosterEditionList.Add("L'Attaque de Néos (STON)");
                BoosterEditionList.Add("Force du Destructeur (FOTB)");
                BoosterEditionList.Add("Evolution Tactique (TAEV)");
                BoosterEditionList.Add("Sombre Révélation 4 (DR4)");
                BoosterEditionList.Add("Assaut du Gladiateur (GLAS)");
                BoosterEditionList.Add("Ténèbres Fantômes (PTDN)");
                BoosterEditionList.Add("Lumière de la Destruction (LOTD)");
                BoosterEditionList.Add("Génèse du Duelliste (TDGS)");
                BoosterEditionList.Add("La Croisée du Chaos (CSOC)");
                BoosterEditionList.Add("La Crise Ecarlate (CRMS)");
                BoosterEditionList.Add("La Rage des Guerriers (RGBT)");
                BoosterEditionList.Add("Ancienne Prophétie (ANPR)");
                BoosterEditionList.Add("Pouvoir de la Poussière d'Etoile (SOVR)");
                BoosterEditionList.Add("Puissance Absolue (ABPF)");
                BoosterEditionList.Add("Les Ténèbres Scintillantes (TSHD)");
                BoosterEditionList.Add("Révolution des Duellistes (DREV)");
                BoosterEditionList.Add("Explosion des Etoiles (STBL)");
                BoosterEditionList.Add("La Tempête de Ragnarök (STOR)");
                BoosterEditionList.Add("Victoire Absolue (EXVC)");
                BoosterEditionList.Add("La Force des Générations (GENF)");
                BoosterEditionList.Add("Onde de Choc Photon (PHSW)");
                BoosterEditionList.Add("L'Ordre du Chaos (ORCS)");
                BoosterEditionList.Add("Le Seigneur de la Galaxie (GAOV)");
                BoosterEditionList.Add("Le Retour du Duelliste (REDU)");
                BoosterEditionList.Add("L'Ascension des Abysses (ABYR)");
                BoosterEditionList.Add("Le Feu du Cosmos (CBLZ)");
                BoosterEditionList.Add("Le Seigneur de la Galaxie Tachyon (LTGY)");
                BoosterEditionList.Add("Le Jugement de la Lumière (JOTL)");
                BoosterEditionList.Add("Spectres de l'Ombre (SHSP)");
                BoosterEditionList.Add("L'Heritage des Braves (LVAL)");
                BoosterEditionList.Add("Origine Primitive (PRIO)");
                BoosterEditionList.Add("L'Alliance des Duellistes (DUEA)");
                BoosterEditionList.Add("Les Nouveaux Challengers (NECH)");
                BoosterEditionList.Add("Les Secrets de l'Eternité (SECE)");
                BoosterEditionList.Add("Les Ames Croisées (CROS)");
                BoosterEditionList.Add("Le Choc des Rebéllions (CORE)");
                BoosterEditionList.Add("Riders à grande vitesse (HSRD)");
                BoosterEditionList.Add("Dimension du Chaos (DOCS)");
                BoosterEditionList.Add("Destructeur de l'ombre (BOSH)");
                BoosterEditionList.Add("Les Victoires Scintillantes (SHVI)");
                BoosterEditionList.Add("L'illusion Des Ténèbres (TDIL)");
                BoosterEditionList.Add("Les aventuriers ailés (WIRA)");
                BoosterEditionList.Add("Invasion Vengeance (INOV)");
                BoosterEditionList.Add("Tempête de rage (RATE)");
                BoosterEditionList.Add("La Crise maximale (MACR)");
                BoosterEditionList.Add("Code des Duellistes (COTD)");

                BoosterPackList.Add("DarkLegend (DLG1)");
                BoosterPackList.Add("Pack Etoile 2013 (SP13)");
                BoosterPackList.Add("Pack Etoile 2014 (SP14)");
                BoosterPackList.Add("Pack Etoile ARC-V (SP15)");
                BoosterPackList.Add("Chasseurs de Numéros (NUMH)");
                BoosterPackList.Add("Les Dragons de la Légende (DRLG)");
                BoosterPackList.Add("Les Dragons de la Légende 2 (DRL2)");
                BoosterPackList.Add("Les Forces Secrètes (THSF)");
                BoosterPackList.Add("Les Superstars Mondiales (WSUP)");
                BoosterPackList.Add("Jump (JUMP)");
                BoosterPackList.Add("Legendary Collection 2: The Duel Academy Years (LCGX)");
                BoosterPackList.Add("Legendary Collection 3: Yugi's World (LCYW)");
                BoosterPackList.Add("Collection Légendaire 4 Méga-Pack (LCJW)");
                BoosterPackList.Add("Collection Légendaire 5D's Méga Pack (LC5D)");
                BoosterPackList.Add("Fusion Pack Premium (PPEP)");
                BoosterPackList.Add("Rétro Pack 1 (RP01)");
                BoosterPackList.Add("Rétro Pack 2 (RP02)");
                BoosterPackList.Add("Méga Pack 14 (MP14)");
                BoosterPackList.Add("Méga Pack 15 (MP15)");
                BoosterPackList.Add("Méga Pack Jaune Râ (RYMP)");
                BoosterPackList.Add("Boîte collection Zexal (ZTIN)");
                BoosterPackList.Add("Collection Premium (PRC1)");
                BoosterPackList.Add("Pack du Millenium (MIL1)");
                BoosterPackList.Add("Movie Pack Corrompu (YMP1)");
                BoosterPackList.Add("The Dark Side of Dimensions Movie Pack (MVP1)");
                BoosterPackList.Add("Collection Tin-Box 7 (CT07)");
                BoosterPackList.Add("Collection Tin-Box 8 (CT08)");
                BoosterPackList.Add("Collection Tin-Box 9 (CT09)");
                BoosterPackList.Add("Collection Tin-Box 10 (CT10)");
                BoosterPackList.Add("Collection Pack du Duelliste (DPCT)");
                BoosterPackList.Add("Exclusivité Jeux-Vidéos (EJV)");
                BoosterPackList.Add("Le Déchaînement des Dragons de la Légende (DRL3)");
                BoosterPackList.Add("Collection Tin-Box 16 (CT13)");
                BoosterPackList.Add("Méga Pack 16 (MP16)");
                BoosterPackList.Add("Les Soldats de la Destinée (DESO)");
                BoosterPackList.Add("Les Exécuteurs Fusion (FUEN)");
                BoosterPackList.Add("Pack Etoile Battle Royal (SP17)");
                BoosterPackList.Add("La Saga des Duellistes (DUSA)");
                BoosterPackList.Add("Boîtes à Collectionner 2004-2006 (CT01-03)");
                BoosterPackList.Add("Boîtes à Collectionner 2007-2009 (CT04-06)");
                BoosterPackList.Add("Boîtes à Collectionner 2014-2015 (CT11-12)");
                BoosterPackList.Add("Evolution des Pendules (PEVO)");
                BoosterPackList.Add("Batailles de Légende : Vengeance de la Lumière (BLLR)");

                ArsenalMysterieuxList.Add("Arsenal Mystérieux 1 (HA01)");
                ArsenalMysterieuxList.Add("Arsenal Mystérieux 2 (HA02)");
                ArsenalMysterieuxList.Add("Arsenal Mystérieux 3 (HA03)");
                ArsenalMysterieuxList.Add("Arsenal Mystérieux 4 (HA04)");
                ArsenalMysterieuxList.Add("Arsenal Mystérieux 5 (HA05)");
                ArsenalMysterieuxList.Add("Arsenal Mystérieux 6 (HA06)");
                ArsenalMysterieuxList.Add("Arsenal Mystérieux 7 (HA07)");

                PackDuellisteList.Add("Jaden (DP1)");
                PackDuellisteList.Add("Chazz Princeton (DP2)");
                PackDuellisteList.Add("Jaden 2 (DP03)");
                PackDuellisteList.Add("Zen Truesdale (DP04)");
                PackDuellisteList.Add("Aster Phoenix (DP05)");
                PackDuellisteList.Add("Jaden 3 (DP06)");
                PackDuellisteList.Add("Jesse Anderson (DP07)");
                PackDuellisteList.Add("Yusei (DP08)");
                PackDuellisteList.Add("Yusei 2 (DP09)");
                PackDuellisteList.Add("Yusei 3 (DP10)");
                PackDuellisteList.Add("Crow (DP11)");
                PackDuellisteList.Add("Yugi (DPYG)");
                PackDuellisteList.Add("Kaiba (DPKB)");
                PackDuellisteList.Add("Bataille Ville (DPBC)");
                PackDuellisteList.Add("Les Rivaux du Pharaon (DPRP)");
                PackDuellisteList.Add("Gardiens Dimensionnels (DPDG)");

                DeckStructureList.Add("Rugissement des Dragons (SD1)");
                DeckStructureList.Add("Folie Zombie (SD2)");
                DeckStructureList.Add("Soufle de Destruction (SD3)");
                DeckStructureList.Add("Fureur des Profondeurs (SD4)");
                DeckStructureList.Add("Triomphe du Guerrier (SD5)");
                DeckStructureList.Add("Le Jugement du Magicien (SD6)");
                DeckStructureList.Add("Forteresse Invincible (SD7)");
                DeckStructureList.Add("Seigneur des Tempêtes (SD8)");
                DeckStructureList.Add("La Rage du Dinosaure (SD09)");
                DeckStructureList.Add("Re-Volt Machine (SD10)");
                DeckStructureList.Add("Resurrection des Grands Dragon (SDRL)");
                DeckStructureList.Add("L'Empereur des Ténèbres (SDDE)");
                DeckStructureList.Add("Monde des Zombies (SDZW)");
                DeckStructureList.Add("Ordre du Magicien (SDSC)");
                DeckStructureList.Add("Attaque des Guerriers (SDWS)");
                DeckStructureList.Add("Mechabot (SDMM)");
                DeckStructureList.Add("Marik (SDMA)");
                DeckStructureList.Add("Légion Dragunité (SDDL)");
                DeckStructureList.Add("Le Sanctuaire Perdu (SDLS)");
                DeckStructureList.Add("Portail du Monde Ténébreux (SDGU)");
                DeckStructureList.Add("Le Choc des Dragons (SDDC)");
                DeckStructureList.Add("Seigneur de Guerre Samouraï (SDWA)");
                DeckStructureList.Add("Le Royaume de l'Empereur des Mers (SDRE)");
                DeckStructureList.Add("Assaut des Rois du Feu (SDOK)");
                DeckStructureList.Add("La Saga du Dragon Blanc Aux Yeux Bleus (SDBE)");
                DeckStructureList.Add("Révolution Cyber Dragon (SDCR)");
                DeckStructureList.Add("Royaume de Lumière (SDLI)");
                DeckStructureList.Add("Déchaînement Geargia (SDGR)");
                DeckStructureList.Add("L'Assaut des HEROS (SDHS)");
                DeckStructureList.Add("Synchro Extrême (SDSE)");
                DeckStructureList.Add("Coffret de la Table Ronde (NKRT)");
                DeckStructureList.Add("Maître des pendules (SDMP)");
                DeckStructureList.Add("Deck Légendaire de Yugi (YGLD)");
                DeckStructureList.Add("Empereur des Ombres (SR01)");
                DeckStructureList.Add("La Résurrection des Véritables Dragons (SR02)");
                DeckStructureList.Add("Decks Legendaires II (LDK2)");
                DeckStructureList.Add("Yugi Muto (SDMY)");
                DeckStructureList.Add("Seto Kaiba (SDKS)");
                DeckStructureList.Add("Domination des pendules (SDPD)");
                DeckStructureList.Add("Le réacteur des machines (SR03)");
                DeckStructureList.Add("La Rage du Dinobroyeur (SR04)");

                DeckDeDemarrageList.Add("Yugi (SDY)");
                DeckDeDemarrageList.Add("Kaiba (SDK)");
                DeckDeDemarrageList.Add("Joey (SDJ)");
                DeckDeDemarrageList.Add("Pegasus (SDP)");
                DeckDeDemarrageList.Add("Yugi Evolution (SYE)");
                DeckDeDemarrageList.Add("Kaiba Evolution (SKE)");
                DeckDeDemarrageList.Add("GX (YSD)");
                DeckDeDemarrageList.Add("Jaden Yuki (YSDJ)");
                DeckDeDemarrageList.Add("Syrus Truesdale (YSDS)");
                DeckDeDemarrageList.Add("5D's (5DS1)");
                DeckDeDemarrageList.Add("5D's 2009 (5DS2)");
                DeckDeDemarrageList.Add("5D's 2010 (5DS3)");
                DeckDeDemarrageList.Add("Avènement des XYZ (YS11)");
                DeckDeDemarrageList.Add("Symphonie XYZ (YS12)");
                DeckDeDemarrageList.Add("V pour Victoire (YS13)");
                DeckDeDemarrageList.Add("Yugi Revient (YSYR)");
                DeckDeDemarrageList.Add("Kaiba Revient (YSKR)");
                DeckDeDemarrageList.Add("Confrontation de l'Espace-Temps (YS14)");
                DeckDeDemarrageList.Add("Yuga & Déclan (YS15)");
                DeckDeDemarrageList.Add("Yuya (YS16)");
                DeckDeDemarrageList.Add("L'attaque du lien (YS17)");

                GoldPremiumList.Add("Collection Gold 1 (GLD1)");
                GoldPremiumList.Add("Collection Gold 2 [2009] (GLD2)");
                GoldPremiumList.Add("Collection Gold 3 (GLD3)");
                GoldPremiumList.Add("Collection Gold 4 Edition Pyramide (GLD4)");
                GoldPremiumList.Add("Collection Gold 5 (GLD5)");
                GoldPremiumList.Add("Gold Premium 1 (PGLD)");
                GoldPremiumList.Add("Gold Premium 2 (PGL2)");
                GoldPremiumList.Add("Premium Gold : Or Infini (PGL3)");

                BattlePackList.Add("Battle Pack: Aube Epique (BP01)");
                BattlePackList.Add("Battle Pack 2: Guerre des géants (BP02)");
                BattlePackList.Add("Guerre des géants - Renforcement (WGRT)");
                BattlePackList.Add("Battle Pack 3: Ligue des Monstres (BP03)");

                TournoiList.Add("Paquet de Tournoi 1 (TP1)");
                TournoiList.Add("Paquet de Tournoi 2 (TP2)");
                TournoiList.Add("Paquet de Tournoi 3 (TP3)");
                TournoiList.Add("Paquet de Tournoi 4 (TP4)");
                TournoiList.Add("Paquet de Tournoi 5 (TP5)");
                TournoiList.Add("Paquet de Tournoi 6 (TP6)");
                TournoiList.Add("Paquet de Tournoi 7 (TP7)");
                TournoiList.Add("Paquet de Tournoi 8 (TP8)");
                TournoiList.Add("Pack des Champions 1 (CP01)");
                TournoiList.Add("Pack des Champions 2 (CP02)");
                TournoiList.Add("Pack des Champions 3 (CP03)");
                TournoiList.Add("Pack des Champions 4 (CP04)");
                TournoiList.Add("Pack des Champions 5 (CP05)");
                TournoiList.Add("Pack des Champions 6 (CP06)");
                TournoiList.Add("Pack des Champions 7 (CP07)");
                TournoiList.Add("Pack des Champions 8 (CP08)");
                TournoiList.Add("Paquet Turbo 1 (TU01)");
                TournoiList.Add("Paquet Turbo 2 (TU02)");
                TournoiList.Add("Paquet Turbo 3 (TU03)");
                TournoiList.Add("Paquet Turbo 4 (TU04)");
                TournoiList.Add("Paquet Turbo 5 (TU05)");
                TournoiList.Add("Paquet Turbo 6 (TU06)");
                TournoiList.Add("Paquet Turbo 7 (TU07)");
                TournoiList.Add("Paquet Turbo 8 (TU08)");
                TournoiList.Add("Paquet Astral 1 (AP01)");
                TournoiList.Add("Paquet Astral 2 (AP02)");
                TournoiList.Add("Paquet Astral 3 (AP03)");
                TournoiList.Add("Paquet Astral 4 (AP04)");
                TournoiList.Add("Paquet Astral 5 (AP05)");
                TournoiList.Add("Paquet Astral 6 (AP06)");
                TournoiList.Add("Paquet Astral 7 (AP07)");
                TournoiList.Add("Paquet Astral 8 (AP08)");
                TournoiList.Add("OTS Pack du Tournoi 1 (OP01)");
                TournoiList.Add("OTS Pack du Tournoi 2 (OP02)");
                TournoiList.Add("OTS Pack du Tournoi 3 (OP03)");
                TournoiList.Add("OTS Pack du Tournoi 4 (OP04)");
                TournoiList.Add("OTS Pack du Tournoi 5 (OP05)");
        }

        public static BoosterInfo InitializeBooster(string name)
        {
            string[] Extension = name.Split('(');
            Extension = Extension[1].Split(')');
            string path = Path.Combine(FormExecution.path, "Assets", "Booster", Extension[0] + ".json");
            return JsonConvert.DeserializeObject<BoosterInfo>(File.ReadAllText(path));
        }
    }
}